{{- if .Values.ingress.enabled }}
# Defines the ingress for the Alfresco Search (Solr) App
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "alfresco-search.fullName" . }}-solr
  labels:
    app: {{ template "alfresco-search.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  annotations:
{{ toYaml .Values.ingress.annotations | indent 4 }}

spec:
  rules:
  - http:
      paths:
      - path: {{ .Values.ingress.path }}
        backend:
          serviceName: {{ template "alfresco-search.fullName" . }}-solr
          servicePort: {{ .Values.service.externalPort }}
{{- end }}